#server:
#  port: 8081

file:
  upload-dir: ./uploads

spring:
  config:
    import: optional:configtree:/run/secrets/

  application:
    name: srpi

  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: a374cd001@smtp-brevo.com
    password: ${sendinblue.smtp.key}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:postgresql://postgres:5432/nitsrpi
    #    url: jdbc:postgresql://localhost:5432/nitsrpi
    username: nitsrpi_user
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

api:
  security:
    token:
      secret: ${jwt.secret}