version: '3.9'

services:
  postgres:
    image: postgres:16.3
    container_name: nitsrpidb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: nitsrpi
    ports:                
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nitsrpi-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:8.9
    container_name: pgadmin4-NIT
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "15432:80"
    depends_on:
      - postgres
    networks:
      - nitsrpi-network
    restart: unless-stopped

  backend:
    build:
      context: ./softwarehub-backend
      dockerfile: Dockerfile
    container_name: nitsrpi-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - nitsrpi-network
    restart: unless-stopped
    env_file:
      - ./softwarehub-backend/.env
    environment:
      JWT_SECRET: my-secret-key
      SPRING_PROFILES_ACTIVE: dev
    volumes:
      - ./softwarehub-backend/uploads:/app/uploads

  # frontend:
  #  build:
  #    context: ./softwarehub_frontend # Caminho para a pasta do Flutter
  #    dockerfile: Dockerfile
  #  container_name: nitsrpi-frontend
  #  ports:
  #    - "80:80" # Acessível em http://localhost
  #  depends_on:
  #    - backend
  #  networks:
  #    - nitsrpi-network
  #  restart: unless-stopped
    
networks:
  nitsrpi-network:
    driver: bridge

volumes:
  pgdata:
